### ISSUE TITLE
docker-compose.yml port is already in use

### ISSUE THREAD

**Issue by Chitranshagarwal2000** [digma-ai/digma#64]
**Describe the bug**
For powershell while updating digma we run the below command 
`iwr https://get.digma.ai/ -outfile docker-compose.yml`
`docker compose up -d`

But if the ports are occupied then we get an error `Error response from daemon: driver failed programming external connectivity on endpoint *-digma-plugin-api-1 (e848753ff91e8c316c6a69192bc5b29f277c1557d8d437ac24d63f83030e2633): Bind for 0.0.0.0:5051 failed: port is already allocated`

**To Reproduce**
If the ports mentioned in the docker-compose.yml file are already occupied then this error occurs

**Expected behavior**
Ideally a port range should be present so if the ports are occupied then a different port can be selected

**Version**
2.0.156+232

**Comment by doppleware** [comment]
Hi @Chitranshagarwal2000, I believe we have solved this issue !
Let me know if the experience is now better and I will close the issue.

**Comment by Chitranshagarwal2000** [comment]
Hello @doppleware ,
This is fixed. Thank you
