### ISSUE TITLE
DOC - Update README with the Youtube Channel link

### ISSUE THREAD

**Issue by ThiagoBfim** [digma-ai/digma#73]
**Is your feature request related to a problem? Please describe.**

There is this sentence: `"You can check out some videos and more info on our Youtube Channel!"` but there is no link to the YouTube Channel.

I tried to install Digma, and I had to search for the YouTube channel, it would be good to have the link in the documentation.

**Describe the solution you'd like**

Add the link to the YouTube channel.

**Comment by doppleware** [comment]
Fixed@ thanks for the comment!
